version: "3.8"
services:
  dreebz-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
